name = "tc-vsme"
assets = { directory = ".output/public" }
compatibility_date = "2026-04-15"
compatibility_flags = ["nodejs_compat"]
main = "src/server.ts"

[observability]
enabled = true

[env.staging]
name = "tc-vsme-staging"
routes = [{ pattern = "staging.tc-vsme.com", custom_domain = true }]

[env.production]
name = "321-vsme"
routes = [{ pattern = "prod.scope321.workers.dev", custom_domain = false }]

