name: Deploy Development

on:
  push:
    branches:
      - dev # Only runs when you push to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Deploy Convex
        # Maps the staging secret to the generic CONVEX_DEPLOY_KEY that the CLI expects
        run: bunx convex deploy
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY_STAGING }}

      - name: Build TanStack App
        run: |
          echo "VITE_CLERK_PUBLISHABLE_KEY=pk_test_Y2xlcmsuZ2VudGxlLmNvZC00LmxjbC5kZXYk" >> .env
          echo "VITE_CONVEX_URL=https://fine-echidna-604.convex.cloud" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY_DEV }}" >> .env
          bun run --bun build

      - name: Build & Deploy Worker (Cloudflare)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_STAGING }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_STAGING }}
          # Tell the action to use your environment with the '--env' flag
          command: deploy --env=""
        #   secrets: |
        #     VITE_CLERK_PUBLISHABLE_KEY
        #     VITE_CONVEX_URL
        # env:
        #   VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_DEV }}
        #   VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL_DEV }}